### ISSUE TITLE
File name template not working on Edge (Chromium)

### ISSUE THREAD

**Issue by constdev1** [gildas-lormeau/SingleFileZ#101]
The file name template options

![msedge_yokV3Od2lJ](https://user-images.githubusercontent.com/89072980/130054600-59206ed2-a404-4276-93cf-18497f86c0a0.png)

are not working as expected. The file name is always an UUID:

![msedge_0nsWlWlKE2](https://user-images.githubusercontent.com/89072980/130054398-0ae046ec-56db-4087-8587-a2a5819fd043.png)

**Comment by gildas-lormeau** [comment]
It's a bug in Chrome, cf. https://bugs.chromium.org/p/chromium/issues/detail?id=892133.

You can circumvent it by disabling the option "Misc. > save pages in background" in SingleFileZ.
