### ISSUE TITLE
Is there any chance we can add webdav as our save destination?

### ISSUE THREAD

**Issue by Kellermaan** [gildas-lormeau/SingleFileZ#103]
Is there any chance we can add webdav as our save destination?

**Comment by gildas-lormeau** [comment]
That's an interesting suggestion. I'll need to learn and play with WebDAV first though :p

**Comment by Kellermaan** [comment]
@gildas-lormeau really appreciate that!

**Comment by gildas-lormeau** [comment]
This feature has (finally) been implemented in the version 1.3.20.

**Comment by Kellermaan** [comment]
wow, thanks a lot.

**Comment by gildas-lormeau** [comment]
You're welcome!
