### ISSUE TITLE
SingleFileZ will not work in Chrome starting January 2023

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFileZ#105]
Google officially announced that extensions using Manifest V2 will not run anymore in Chrome starting January 2023, see https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/.

However, the Manifest V3 introduces some regressions. At the time of writing this issue report, (at least) this bug https://bugs.chromium.org/p/chromium/issues/detail?id=1227761 prevents SingleFileZ to work with Manifest V3 in Chrome because it won't be able to read (and unzip) archives from the filesystem.

**Comment by dotproto** [comment]
I understand that crbug.com/1227761 prevents SingleFileZ from using XMLHttpRequest or fetch() to request a file:// URI from within an extension's service worker, but is there a reason the extension couldn't work around this limitation by spawning a temporary window to perform this work?

**Comment by gildas-lormeau** [comment]
So, when a user would drag and drop a saved file or double-click from his filesystem, a new window will open and close itself immediately during the time the page is decompressed? This sounds like a very bad user experience. I'm not even sure this is technically doable.

**Comment by gildas-lormeau** [comment]
@dotproto BTW, I just started to try to port SingleFile to Manfest V3. Said politely, it's painful. I can't believe that `chrome.i18n.getMessage` can't be used in the service worker. How are we supposed to initialize/change menu entries and the button label with localized strings? I don't see any information about this issue here https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/.

**Comment by gildas-lormeau** [comment]
The regression in Chrome has been fixed, see https://bugs.chromium.org/p/chromium/issues/detail?id=1227761. It should be possible to make SingleFileZ (almost) compatible with the Manifest V3.

**Comment by curiousleo** [comment]
@gildas-lormeau it may be worth updating the [Download section of the README](https://github.com/gildas-lormeau/SingleFileZ#download), which refers to this issue:

> It is _not recommended_ to use SingleFileZ on Chrome because it will stop working starting January 2023 (see https://github.com/gildas-lormeau/SingleFileZ/issues/105).

**Comment by PatrikMazanek** [comment]
Or if there are still some limitations, maybe provide the details?

**Comment by J-HS-L** [comment]
Any more clarity with all of this? Porting underway?

**Comment by gildas-lormeau** [comment]
@J-HS-L I did not start the work yet. Note however that Google changed the MV2 support timeline recently. Now, the deadline will be January 2024, see https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/.

**Comment by J-HS-L** [comment]
@gildas-lormeau 

Thank you very much for your response...
Is there a discussion thread I can follow RE this work? 
(since this thread is now closed)

**Comment by gildas-lormeau** [comment]
@J-HS-L J-H

You can follow this issue, I'll keep it updated.
