### ISSUE TITLE
Unable to run "npm outdated" after manually install SingleFileZ

### ISSUE THREAD

**Issue by XOKP** [gildas-lormeau/SingleFileZ#106]
I followed the instruction of manual installation, downloaded and installed SingleFileZ globally with npm.

`npm install -g "gildas-lormeau/SingleFileZ#master"`

This causes error to `npm outdated` afterward.

`npm outdated -g --depth=0`

> npm ERR! code ENOVERSIONS
> npm ERR! No versions available for single-filez
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/Username/.npm/_logs/2021-09-24T07_49_20_283Z-debug.log

Full log (/Users/Username/.npm/_logs/2021-09-24T07_49_20_283Z-debug.log):

> 0 verbose cli [
> 0 verbose cli   '/opt/local/bin/node',
> 0 verbose cli   '/opt/local/bin/npm',
> 0 verbose cli   'outdated',
> 0 verbose cli   '-g',
> 0 verbose cli   '--depth=0'
> 0 verbose cli ]
> 1 info using npm@7.24.0
> 2 info using node@v16.10.0
> 3 timing npm:load:whichnode Completed in 0ms
> 4 timing config:load:defaults Completed in 1ms
> 5 timing config:load:file:/opt/local/lib/node_modules/npm/npmrc Completed in 0ms
> 6 timing config:load:builtin Completed in 1ms
> 7 timing config:load:cli Completed in 2ms
> 8 timing config:load:env Completed in 1ms
> 9 timing config:load:file:/Users/Username/Dropbox/Shell/usage/.npmrc Completed in 0ms
> 10 timing config:load:project Completed in 1ms
> 11 timing config:load:file:/Users/Username/.npmrc Completed in 0ms
> 12 timing config:load:user Completed in 0ms
> 13 timing config:load:file:/opt/local/etc/npmrc Completed in 0ms
> 14 timing config:load:global Completed in 1ms
> 15 timing config:load:validate Completed in 0ms
> 16 timing config:load:credentials Completed in 1ms
> 17 timing config:load:setEnvs Completed in 1ms
> 18 timing config:load Completed in 9ms
> 19 timing npm:load:configload Completed in 9ms
> 20 timing npm:load:setTitle Completed in 3ms
> 21 timing npm:load:setupLog Completed in 1ms
> 22 timing config:load:flatten Completed in 3ms
> 23 timing npm:load:cleanupLog Completed in 2ms
> 24 timing npm:load:configScope Completed in 0ms
> 25 timing npm:load:projectScope Completed in 1ms
> 26 timing npm:load Completed in 20ms
> 27 timing arborist:ctor Completed in 1ms
> 28 timing command:outdated Completed in 1202ms
> 29 verbose type tag
> 30 verbose stack single-filez: No versions available for single-filez
> 30 verbose stack     at pickManifest (/opt/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:140:25)
> 30 verbose stack     at module.exports (/opt/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:187:16)
> 30 verbose stack     at Outdated.getOutdatedInfo (/opt/local/lib/node_modules/npm/lib/outdated.js:224:22)
> 30 verbose stack     at async Promise.all (index 2)
> 30 verbose stack     at async Outdated.outdated (/opt/local/lib/node_modules/npm/lib/outdated.js:83:5)
> 31 verbose cwd /Users/Username/Dropbox/Shell/usage
> 32 verbose Darwin 20.6.0
> 33 verbose argv "/opt/local/bin/node" "/opt/local/bin/npm" "outdated" "-g" "--depth=0"
> 34 verbose node v16.10.0
> 35 verbose npm  v7.24.0
> 36 error code ENOVERSIONS
> 37 error No versions available for single-filez
> 38 verbose exit 1

**Comment by gildas-lormeau** [comment]
I guess this issue is obsolete now. The CLI has now its own repository, see https://github.com/gildas-lormeau/single-filez-cli and https://www.npmjs.com/package/single-filez-cli.
