### ISSUE TITLE
CLI option --output-directory does not work

### ISSUE THREAD

**Issue by andrewdbate** [gildas-lormeau/SingleFileZ#108]
When I attempt to use the `--output-directory` option I get an error. I am using docker on Windows 10 from the Command Prompt.

```
$ docker run -v %cd%:/usr/src/app/out singlefilez "https://www.wikipedia.org" "out.html" --output-directory=mydir
outputDirectory.endsWith is not a function URL: https://www.wikipedia.org
Stack: TypeError: outputDirectory.endsWith is not a function
    at getFilename (/usr/src/app/node_modules/single-filez/cli/single-file-cli-api.js:256:42)
    at capturePage (/usr/src/app/node_modules/single-filez/cli/single-file-cli-api.js:230:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runNextTask (/usr/src/app/node_modules/single-filez/cli/single-file-cli-api.js:149:20)
    at async Promise.all (index 0)
    at async capture (/usr/src/app/node_modules/single-filez/cli/single-file-cli-api.js:119:2)
    at async run (/usr/src/app/node_modules/single-filez/cli/single-filez:57:2)
```

I think this is a bug. Even if I have used the arguments incorrectly I should still now get a stack trace.

Many thanks!

**Comment by gildas-lormeau** [comment]
Thank you for the report. The issue was due to the fact that `--output-directory` is already defined in the `DockerFile` faile and the fact that the library I to handle parameters transform multiple occurrences of the same parameter into an `Array`. That's why the `endsWith` method did not exist. To fix the issue, I added some code to concatenate the path defined in the `DockerFile` and the provided via the CLI.

**Comment by gildas-lormeau** [comment]
I'm going to add some code to test if the path provided via the CLI whern using Docker begins with "/" to solve this issue, it should be acceptable I guess.

**Comment by andrewdbate** [comment]
Thanks! It seems sensible to me that if the path begins with `/` then it should be treated as absolute from the root of the container, otherwise it should be treated as relative.

**Comment by gildas-lormeau** [comment]
You're welcome, I just pushed the changes on Docker.

**Comment by andrewdbate** [comment]
I've tested `latest` and it works for me. Many thanks again!
