### ISSUE TITLE
CLI option --dump-content defaults to true but help page says default is false

### ISSUE THREAD

**Issue by andrewdbate** [gildas-lormeau/SingleFileZ#109]
The CLI option `--dump-content` defaults to `true`. However, the help page (from `--help`) says the following:
```
--dump-content     Dump the content of the processed page in the console  [boolean] [default: false]
```

I ran into this issue because I was trying to save pages with a generated output filename (using the filename template). For this, I need to set `--dump-content=false` as explained on [this page](https://github.com/gildas-lormeau/SingleFileZ/blob/master/cli/README.MD), however, the help page says the default is false (see above). Without the option `--dump-content=false` set (i.e., the default behaviour), the page is printed to the console instead of being saved to file.

Many thanks.

**Comment by gildas-lormeau** [comment]
Well, I was expecting users would check the Dockerfile because that's what I would do, as a "devops user". I know that the way SingleFile and SingleFileZ are packaged (through Docker) is not very user-friendly though.
