### ISSUE TITLE
Stack: ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by Fandaal** [gildas-lormeau/SingleFileZ#118]
Installed as Node.js module globally, with all dependencies -
npm install -g "gildas-lormeau/SingleFileZ#master"
In args.js "back-end": "jsdom"
Does not work

> NodeJS\node_modules\single-filez\cli>single-filez https://www.wikipedia.org/
> TextEncoder is not defined URL: https://www.wikipedia.org/
> Stack: ReferenceError: TextEncoder is not defined
>     at Kt (eval at getPageData (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\back-ends\jsdom.js:71:6), <anonymous>:1:113480)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async Object.e.getPageData (eval at getPageData (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\back-ends\jsdom.js:71:6), <anony
> mous>:1:417202)
>     at async getPageData (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\back-ends\jsdom.js:83:19)
>     at async Object.exports.getPageData (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\back-ends\jsdom.js:39:10)
>     at async capturePage (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\single-file-cli-api.js:228:20)
>     at async runNextTask (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\single-file-cli-api.js:149:20)
>     at async Promise.all (index 0)
>     at async capture (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\single-file-cli-api.js:119:2)
>     at async run (C:\Portable\PortableApps\NodeJS\node_modules\single-filez\cli\single-filez:57:2)

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce and fix the issue.
