### ISSUE TITLE
Do SingleFileZ support the command line?

### ISSUE THREAD

**Issue by LampScript** [gildas-lormeau/SingleFileZ#12]
SingleFileZ saving file is smaller than SingleFile, but it's seems doesn't support command line interface

**Comment by gildas-lormeau** [comment]
Actually, I did not include the CLI yet because it was not a priority but I guess copying and pasting the /cli/ folder from SingleFile should work. Stay tuned ;)

**Comment by LampScript** [comment]
thanks
