### ISSUE TITLE
HTML page missing external media (from different domain)

### ISSUE THREAD

**Issue by claudiobizzotto** [gildas-lormeau/SingleFileZ#120]
Thanks for this project.

Not sure if this is a bug or a feature request, but the Firefox extension doesn't seem to save local copies of media, such as images, whose sources are on a different domain than the original web page that I want to save.

**Comment by gildas-lormeau** [comment]
It's unfortunately a security issue in browsers. You can use a local HTTP server to circumvent it, see https://gist.github.com/willurd/5720255 for some of them.

**Comment by claudiobizzotto** [comment]
Thanks. That solution is not ideal, though, because I'd prefer to read the content without the need of a web server of any kind (and possibly even convert to ePub). There's also the possibility that the content may disappear from the original website/host, in which case I'd like to have a local copy I could use.
