### ISSUE TITLE
"includeBOM": true, ----- invalid

### ISSUE THREAD

**Issue by newsdos** [gildas-lormeau/SingleFileZ#125]
"includeBOM": true, ----- invalid

**Comment by gildas-lormeau** [comment]
What do you mean?

**Comment by gildas-lormeau** [comment]
I need more details about this issue otherwise I won't be able to fix it...

**Comment by gildas-lormeau** [comment]
Today, the BOM is added only in the `index.html` file in the zip. Out of curiosity, why do you need the BOM?
