### ISSUE TITLE
MacOS Archive Utility (default) can't extract file

### ISSUE THREAD

**Issue by rmst** [gildas-lormeau/SingleFileZ#131]
![image](https://user-images.githubusercontent.com/7987756/174394492-c8f874a3-d3e4-4ca3-9002-812031f65b1d.png)

Used SingleFileZ/master to download the file and then renamed the extension from .html to .zip and got this. Am I doing anything wrong or is this a bug?

**Comment by rmst** [comment]
Okay seems to be an issue just with MacOS' Archive Utility. With Python's zipfile the extraction works

**Comment by gildas-lormeau** [comment]
I confirm this is a bug in MacOS utility which does not data descriptor signatures in zip files, see "4.3.9  Data descriptor" for more info here: https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT. I should be able to circumvent it though.

**Comment by gildas-lormeau** [comment]
Did Apple fix the issue?

**Comment by rmst** [comment]
No, I just closed it because it's an Apple bug not a SingleFile bug

**Comment by gildas-lormeau** [comment]
Starting with SingleFileZ version 1.3.23, saved pages should be opened in MacOS Archive Utility.
