### ISSUE TITLE
is it possible to add option to turn file:// to SingleFile ?

### ISSUE THREAD

**Issue by 0rt** [gildas-lormeau/SingleFileZ#132]
I have a lot of page saved by old scarpbook, and I want to changed them to single file by singlefilez, but due to the limitation of security, it is not allowed. Can the user override the limitation by some prefs or setting?
Or any idea of how I can get the job done?

I am using Firefox 100 and singlefilez

**Comment by gildas-lormeau** [comment]
You can achieve this by running an HTTP server and save pages in http. Here is a list of useful commands to run an HTTP server locally: https://gist.github.com/willurd/5720255.

**Comment by 0rt** [comment]
Thank you. I host them by your instruction link and saved to singlefile!

**Comment by gildas-lormeau** [comment]
@0rt I'm glad to hear it :)
