### ISSUE TITLE
Differences to Chrome's (new?) MHTML page capture

### ISSUE THREAD

**Issue by rmst** [gildas-lormeau/SingleFileZ#134]
I was curious, is SingleFile(Z) doing anything differently than Chrome's https://developer.chrome.com/docs/extensions/reference/pageCapture/?

For Chromium-based browsers, could SingleFile(Z) be simplified by getting the pageCapture MHTML output and converting that into a regular HTML file? MHTML seems to be a very simple format.

**Comment by gildas-lormeau** [comment]
Today, MHTML is almost a proprietary format from my point of view. This is a big drawback for an archiving format.

**Comment by rmst** [comment]
Thanks for the nice reference! Agreed, that makes sense. On the other hand it's a pretty simple, human-readable format which, unlike the html/zip approach, doesn't require modifying the urls on the page.

It probably also has the unfair advantage that it's implemented natively and the browser doesn't have to re-download the files

**Comment by rmst** [comment]
> Note also that SingleFile existed before Google decided to add the support of MHTML in Chrome

Who knows perhaps it was Singlefile that finally pushed them to implement it / turn the MHTML on by default :P

**Comment by gildas-lormeau** [comment]
What I can tell you is that Google is more or less considering the opposite today, see https://crbug.com/1235248. Note that neither Firefox nor Safari currently support MHTML and that it's very unlikely that this will happen.
