### ISSUE TITLE
SingleFileZ doesn't work anymore

### ISSUE THREAD

**Issue by DenB10** [gildas-lormeau/SingleFileZ#135]
Hello,
Since version 1.3.23, SingleFileZ doesn't want to work on my computer. On any page I want to save, I get the same answer: "This page cannot be saved with SingleFileZ". I'm using Firefox 91.11.0esr on Windows 7 64-bit.
I have tried an installation in a blank profile but I still have the same problem. What can I do? Revert to version 1.3.22 which works perfectly well? Thank you!
Denis

**Comment by gildas-lormeau** [comment]
Sorry, I reverted the changes. It should work in the version 1.3.25 that I just published.

**Comment by DenB10** [comment]
Works, thanks!
