### ISSUE TITLE
Default file extension

### ISSUE THREAD

**Issue by maliayas** [gildas-lormeau/SingleFileZ#138]
IMHO `.zip.html` would be a better default extension for SingleFilez as it signals the content of the file better.

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion, I totally agree with you. I'm still wondering why I did not make this choice.

**Comment by gildas-lormeau** [comment]
It's fixed in the version 1.3.27 I just uploaded on the stores.

**Comment by maliayas** [comment]
Thanks very much. I noticed an edge case: If a file already exists with the same name, it enumerated like this: `..... (29.07.2022).zip(1).html` instead of `.......(29.07.2022) (1).zip.html`.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. It looks like the edge case is a bug in the browser. I cannot fix it in the extension unfortunately.

**Comment by maliayas** [comment]
Oh, makes sense. Thanks anyway.

**Comment by gildas-lormeau** [comment]
I did a test in Firefox and Chrome and I get the same result. I suspect a bug in Windows in my case.
