### ISSUE TITLE
webDAV saving: zip.html and letter after sharp will be discard when title included "#" 

### ISSUE THREAD

**Issue by ms300** [gildas-lormeau/SingleFileZ#139]
saving the page with sharp included in the title such as `https://www.google.com.hk/search?q=2%233` or this issue page to webDAV will cause the letter after the sharp discarded.

expected filename: `2#3 - Google Search.zip.html`
actual filename: `2`

It is probably because sharp is a special character for URL: https://en.wikipedia.org/wiki/URI_fragment, the filename should be encoded when passing to webDAV server.

**Comment by gildas-lormeau** [comment]
If I'm not wrong, this issue should be fixed.

**Comment by ms300** [comment]
Thanks!
