### ISSUE TITLE
Whale browser compatibility 

### ISSUE THREAD

**Issue by lepermagpie** [gildas-lormeau/SingleFileZ#145]
I'm having trouble installing SingleFileZ on [Naver Whale](https://whale.naver.com/en/), a chromium-based browser, whether by using the Chrome store or loading it unpacked. I get "Invalid manifest" or "could not load manifest". I understand this problem seems very trivial as I can just use Edge or Chrome but I've been trying to reduce my dependence on Microsoft and Google in any way I can. I've installed it on Brave, another alternative chromium browser, but I much prefer the UI and features of Whale. I'm guessing I could bypass this by editing the manifest itself? Any help would be appreciated.

**Comment by gildas-lormeau** [comment]
Indeed, for some reasons this browser does not like the presence of the key `sidebar_action` in the [manifest.json](https://github.com/gildas-lormeau/SingleFileZ/blob/a577fd188dde0d212f521b71799fbf6087c52574/manifest.json) file, see below.

```json
  ...
  "sidebar_action": {
    "browser_style": true,
    "default_title": "SingleFileZ",
    "default_panel": "src/ui/pages/panel.html",
    "default_icon": "src/ui/resources/icon_128.png",
    "open_at_install": false
  },
  ...
```
This key is used by Opera and all browsers that supports sidebars (e.g. Firefox).

To circumvent this issue, you have to install the extension manually:
1. Download the latest version as a zip here: https://github.com/gildas-lormeau/SingleFileZ/archive/refs/heads/master.zip
2. Unzip it somewhere on your disk
3. Open the `manifest.json` file in the root folder and remove the `sidebar_action` and its value (see code above).
4. Open `whale://extensions/`
5. Click on the button `Developer mode` at the bottom of the page
6. Click on the button `Load unpacked` at the right
7. Select the folder where you unzipped the extension

**Comment by lepermagpie** [comment]
Thank you!
