### ISSUE TITLE
Can i save a page to a folder instead of repo root via saving to github?

### ISSUE THREAD

**Issue by baddate** [gildas-lormeau/SingleFileZ#149]
I really like this tool, it saved my workflows. but when i use the `saving to github` option, all my saved pages were saved to repo root dir, it doesn't look good when saved pages is too many.

so is it possible to add some new features like this?

btw, generating a random commit message may be better.

**Comment by gildas-lormeau** [comment]
Sorry for the very late answer, you can include the folder via the `File name > template` option, e.g. `SingleFile/{page-title} ({date-locale} {time-locale}).html` to save pages in the `SingleFile` folder.
