### ISSUE TITLE
SingleFileZ ne marche plus

### ISSUE THREAD

**Issue by guicaz** [gildas-lormeau/SingleFileZ#155]
Cela fait un moment maintenant que je n’arrive plus à utiliser SingleFileZ. 
J’ai ce problème sur windows 8.1 avec la dernière version de Firefox, mais aussi sur ubuntu 23.04 avec Firefox, Waterfox-Classic, Waterfox G5, tous sur les dernières versions disponible, chaque fois que je clique sur le bouton « save page with SingleFileZ » absolument rien ne se passe. Par contre, SingleFile lui, fonctionne parfaitement. Je ne sais pas ce qui cause ce problème, mais même si je retourne plusieurs versions en arrière, ça ne fonctionne pas. J’ai essayé d’installer jusqu’à la version 1.3.25 qui est la dernière ancienne version disponible dans les Add-Ons sur mozilla, mais ça fait la même chose.

**Comment by gildas-lormeau** [comment]
C'est peut-être un conflit avec une autre extension. Avez-vous essayé de les désactiver temporairement pour vérifier cette piste ?

**Comment by guicaz** [comment]
Je viens d'essayer de tout désactiver sur un nouveau profile, réinstallant l'add-on et en laissant tout par défaut, cela fonctionne. 

Après avoir re-installer toute mes add-ons, cela fonctionne toujours. Il doit y avoir une option que je coche qui casse l'application ? Pour essayer j'ai remis les options par défaut là où ça ne marchait pas, et en effet ça remarche. Je me demande quelle option casse l'extension ? Je vous joint mes options à ce message.
[singlefilez-settings-2023-06-23T21_11_53.144Z.txt](https://github.com/gildas-lormeau/SingleFileZ/files/11853092/singlefilez-settings-2023-06-23T21_11_53.144Z.txt)

**Comment by guicaz** [comment]
J'ai re-coché les options manuellement au lieu de les importer et tout a l'air de fonctionner. Très étrange, mais je suppose qu'exporter et importer les options causent un problème chez moi. Peut-être le cas aussi pour d'autre, mais je suppose qu'on peut marquer le problème comme résolu. Merci de votre aide.
