### ISSUE TITLE
Issue with the infobar tooltip

### ISSUE THREAD

**Issue by DenB10** [gildas-lormeau/SingleFileZ#165]
Hello,
Since version 1.3.64, the infobar of a saved page no longer displays the url of the source page in the tooltip.
I get instead : "Open the source URL: undefined".
Note that there's no such issue in the editor when the option to display the infobar is checked.
Please let me know if the problem is due to a wrong configuration on my side.
Kind regards

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce the bug. This is a regression due to a refactoring of the infobar. I fixed it. The fix will be available in the version `1.3.68` I've  just uploaded on the stores.

**Comment by DenB10** [comment]
Merci pour votre réactivité !

**Comment by gildas-lormeau** [comment]
De rien, c'est gentil de votre part d'avoir pris le temps de me faire part de cette regression malheureuse ;)
