### ISSUE TITLE
Can add the option to view the original webpage before or after the webpage

### ISSUE THREAD

**Issue by NOBB2333** [gildas-lormeau/SingleFileZ#169]
Sometimes we save html some thing lost we need to sava again, but can't find origin link, can add some direct to origin html 
like 
有时我们保存html丢失的一些东西需要重新保存，但找不到原始链接，可以直接添加一些到原始html
![image](https://github.com/gildas-lormeau/SingleFileZ/assets/72846817/4d013d03-118a-4af4-ad73-d5f3d73cf140)

**Comment by gildas-lormeau** [comment]
You have to display the infobar to fix this issue.
