### ISSUE TITLE
Add page-url to file saved name option 

### ISSUE THREAD

**Issue by saadb** [gildas-lormeau/SingleFileZ#17]
It would be grand if the option page-url is added when html page is saved as single file
You already have page-title as option

**Comment by gildas-lormeau** [comment]
@saadb Thanks for the suggestion. Note that some characters like "/", ":" will be replaced with "_" because they are not valid in filenames.

**Comment by saadb** [comment]
I assume that you will add the above feature to SingleFile add-on too! Yeah!

**Comment by gildas-lormeau** [comment]
Yes, stay tuned ;)

**Comment by gildas-lormeau** [comment]
@saadb Well... Actually the variable already exists but I did not find it :p. I guess there are too much variables! The variable you want is `{url-href}`

**Comment by saadb** [comment]
Thank you, it worked

**Comment by gildas-lormeau** [comment]
Great!
