### ISSUE TITLE
Infobar completely useless if displayed in annotation editor

### ISSUE THREAD

**Issue by DenB10** [gildas-lormeau/SingleFileZ#174]
Hello,

I've noticed that if you check the "Annotation editor > display the infobar" option, the infobar does appear when you click on the "Annotate and save the page..." command, but the links it contains ("Close" and "Open source URL") are not clickable, which makes the infobar completely useless.
Is this normal behavior or a bug?

Best regards

**Comment by gildas-lormeau** [comment]
Thank you, it was actually a known issue. It will be fixed in the version. Meanwhile, you can use the context menu to open the link in the infobar.
