### ISSUE TITLE
The info panel is not displayed in previously saved files

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#175]
Firefox 119
Windows 11
After the 1.4.16 build (17 - 25), the info panel is not displayed in files saved in build 1.4.16 and earlier.

**Comment by gildas-lormeau** [comment]
Thank you and sorry for the inconvenience, it's fixed in the version 1.4.6 which is available for download.

**Comment by kramola-RU** [comment]
Great! Thank you very much!
