### ISSUE TITLE
Info-Panel

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#18]
a few months ago I saved the page via **SF** (with info panel).

now I opens saved page in FF (with SF**Z**) but the info panel is not displayed.

Is it possible to fix this?

**Comment by gildas-lormeau** [comment]
Well, the fact that SingleFileZ was able to display the infobar of pages saved with SingleFile was actually a bug. For example, if you used the 2 extensions and disabled the option "display infobar" in one extension but not the other one, the infobar was always displayed and this was not what a user would expect. I'll try to find a way to fix your issue. Stay tuned ;)

**Comment by kramola-RU** [comment]
thanks a lot

You are the best

**Comment by gildas-lormeau** [comment]
Here is an extension dedicated to this feature that you can install by:
 * unzipping the file somewhere on your disk,
 * opening about:debugging,
 * selecting the `manifest.json` file of the unzipped file

The extension will uninstall itself each time you restart the browser so it's not very practical as is. Before I sign it on AMO, could you please tell me if this solution is acceptable for you?

[sf-infobar-extension.zip](https://github.com/gildas-lormeau/SingleFileZ/files/3523003/sf-infobar-extension.zip)

**Comment by kramola-RU** [comment]
Yes, it works.
everything is fine (at glance)
I can see **SF**-.html`s info-bar.

thanks
thanks
thanks

**Comment by gildas-lormeau** [comment]
Great! I'm glad you're happy with it :)

I'll sign it tomorrow and upload the .xpi file here.

**Comment by kramola-RU** [comment]
Thank You!

**Comment by gildas-lormeau** [comment]
Here is the .xpi file. You can install it by unzipping the attached file, selecting "Install Add-on From File..." in the menu at the top right of the page about:addons and selecting the .xpi file.

[sf_infobar-0.0.1-an+fx.xpi.zip](https://github.com/gildas-lormeau/SingleFileZ/files/3525448/sf_infobar-0.0.1-an%2Bfx.xpi.zip)

**Comment by kramola-RU** [comment]
Thank you very much.
But why don't you want to embed this script into the SF and SFZ?

**Comment by gildas-lormeau** [comment]
You're welcome. I can't embed it because it would be considered as a bug, i.e. the one I described in my first answer.

**Comment by kramola-RU** [comment]
If the bug is useful, then this is not a bug, but a feature :)

**Comment by gildas-lormeau** [comment]
It's useful until you don't want to display the infobar in one of the extensions ;)

**Comment by kramola-RU** [comment]
this extension is useful -- ok, i agree

but embeded ifobar - maybe useful too (no need additional addons)

**Comment by gildas-lormeau** [comment]
You can already do that, cf. the option "HTML Content > include the infobar in the saved page".

**Comment by kramola-RU** [comment]
correct translation is:
1. "добавление информационной панели в сохраняемую страницу"
**2. "добавлять информационную панель в сохраняемую страницу"**

2-nd is prefer

**Comment by gildas-lormeau** [comment]
Thank you! I just released version 0.2.31 (1.11.31 for SingleFile) with the new translation of the label.

**Comment by gildas-lormeau** [comment]
I'm also closing this issue because I consider it as fixed. Feel free to re-open it if necessary.
