### ISSUE TITLE
The "Drag-Select Link Text" addon do not works on pages saved using SFZ-1.4.42

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#182]
In Firefox I use the "Drag-Select Link Text" addon.
This addon stopped working on pages saved using SFZ-1.4.42.
On pages saved using SFZ-1.4.41 this addon works fine.
Could you fix it, please?

**Comment by gildas-lormeau** [comment]
Thank you, I think I have identified and fixed the cause of the issue. The fix will be available in the next version.

**Comment by kramola-RU** [comment]
Thank you very much !

**Comment by gildas-lormeau** [comment]
The new version is available for download.

**Comment by kramola-RU** [comment]
works fine !
Thank You
