### ISSUE TITLE
V1.4.44 doesn't save notes

### ISSUE THREAD

**Issue by DenB10** [gildas-lormeau/SingleFileZ#183]
Hello Gildas,

It seems that the latest version of SingleFileZ (1.4.43 and not 1.4.44 as I wrote in title) no longer saves notes created in an edited page.

At first I thought it was a configuration problem with my Firefox, so I deactivated all my extensions, but the problem persists. Note that it has no problem saving highlights, however.

Can you reproduce it?

**Comment by gildas-lormeau** [comment]
Thank you for the bug report. I confirm I was able to reproduce the regression. It's fixed in the version 1.4.44 I've just published on the store.
