### ISSUE TITLE
The iframe base64 in the generated page is too large, resulting in a blank page

### ISSUE THREAD

**Issue by zhang-glitch** [gildas-lormeau/SingleFileZ#188]
When downloading this website, the base64 url generated for the iframe in the pop-up section is too large, causing the pop-up section to not be displayed.
![image](https://github.com/gildas-lormeau/SingleFileZ/assets/64189537/3565357a-b990-448e-a839-f168c5e2500f)

generated page

![image](https://github.com/gildas-lormeau/SingleFileZ/assets/64189537/e490f2a9-f3f7-43a9-8bd2-5d7ff9d665ee)

Then convert the base64 url to a blob url and you can display it directly.
```js
const base64Url = ""
const iframe = document.querySelector('iframe');
iframe.src = base64Url // blank

// base64 url to blob url
var byteCharacters = atob(base64Url.split(',')[base64Url.split(',').length - 1]);
var byteNumbers = new Array(byteCharacters.length);
for (var i = 0; i < byteCharacters.length; i++) {
    byteNumbers[i] = byteCharacters.charCodeAt(i);
}
var byteArray = new Uint8Array(byteNumbers);
console.log(base64Url.split(',')[0].split(":")[1]);
var file = new Blob([byteArray], { type: base64Url.split(',')[0].split(":")[1] });
var fileURL = URL.createObjectURL(file);

iframe.src = fileURL // display
```
base64 url，blank
![image](https://github.com/gildas-lormeau/SingleFileZ/assets/64189537/9b89dea0-519e-48cb-a09d-7fd2d3536c48)
blob url , display
![image](https://github.com/gildas-lormeau/SingleFileZ/assets/64189537/0e8d2629-d6e2-4f33-9bb4-e5ff86fc9117)

**Comment by zhang-glitch** [comment]
website URL： https://cms.demo.fastadmin.net/admin.php/index/login

**Comment by gildas-lormeau** [comment]
Thank you, I implemented an optimization where the top-level frames will use Blob URIs instead of data URIs when self-extracting the page. It should fix the issue you described. The fix will be available in the next version of **SingleFile**. In order to be compliant with MV3 among other things, SingleFileZ has been merged into SingleFile and is not maintained anymore.
