### ISSUE TITLE
data src endcoded by base64 limit to 2M in chrome

### ISSUE THREAD

**Issue by dijiang** [gildas-lormeau/SingleFileZ#189]
[内容管理 (8).zip](https://github.com/gildas-lormeau/SingleFileZ/files/15289669/8.zip)

as in example file saved by singleFileZ，iframe can't loaded because data src endcoded by base64 limit to 2M in chrome。

this example file can opened by firefox as it has no such limit

**Comment by gildas-lormeau** [comment]
See https://github.com/gildas-lormeau/SingleFileZ/issues/188
