### ISSUE TITLE
Auto-save function doesn't work

### ISSUE THREAD

**Issue by nobucc** [gildas-lormeau/SingleFileZ#19]
Thanks a bunch for making great software. I'm writing this to seek your advice.
I'm using `SingleFileZ 0.2.35` on `Google Chrome 76.0.3809.132`.

I've been using the auto-save function for couples of weeks and it worked pretty well. But the function stops working suddenly. I rebooted my computer and reinstalled the extension, but the auto-save function is still not working. I still be able to save the page by manually clicking the extension's button on my tool bar. Another problem I found is that the change of auto-save setting doesn't (seem to be) applied. Even if I right-click the extension's button and change the auto-save setting (let's say from `Auto-save all tabs` to `Auto-save unpinned tabs`), the setting changes back to `Auto-save all tabs` after reloading the page.

[This is my setting.](https://github.com/gildas-lormeau/SingleFileZ/files/3570811/singlefilez-settings.txt) `User-Setting-01` is the default profile. Please let me know if you need any other information.

Thank you in advance.

**Comment by gildas-lormeau** [comment]
I'm sorry, it's a regression I introduced recently. It's fixed in the version 0.2.36 that I just deployed. Unfortunately, unlike SingleFile, Google is imposing me a delay of 7 days to publish SingleFileZ on the store. So you'll have to wait for one week. You can install it manually meanwhile.

**Comment by nobucc** [comment]
Thank you for your quick response! I got it.
Please keep up the good work!

**Comment by gildas-lormeau** [comment]
You're welcome!
