### ISSUE TITLE
Hyperlinks in a saved files

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#22]
For example, I saved the selection:
http://forum.ru-board.com/topic.cgi?forum=5&topic=50187&start=720#12

Attached file:
[Ru.Board.htmlz.zip](https://github.com/gildas-lormeau/SingleFileZ/files/3581658/Ru.Board.htmlz.zip)

Why doesn’t the click on the “**Отправлено:**” button work?

![123](https://user-images.githubusercontent.com/51376332/64392033-ad4edb00-d053-11e9-9ed0-a52553d376ca.png)

**Comment by gildas-lormeau** [comment]
On http://forum.ru-board.com, this link allows the user to go to the top of the post. In the saved page, you get the same behavior. If you reduce the height of your browser or select multiple posts, you see that clicking on this link allows you to go to the top of the corresponding post. It works as expected.

**Comment by kramola-RU** [comment]
> It works as expected

No. I expect to go at "LIVE" version the page.

I use SFZ now. But when I used SF, **"Отправлено:"**-button worked as expected.

Attached file (button works as expected) :
[SF -- Ru.Board.html.zip](https://github.com/gildas-lormeau/SingleFileZ/files/3584821/SF.--.Ru.Board.html.zip)

**Comment by gildas-lormeau** [comment]
Did you change any option in SingleFile? I'm unable to get a link to the "LIVE" version of the page when I try to save the selection of a post.

**Comment by kramola-RU** [comment]
> Did you change any option in SingleFile?

Yes.
My settings for SF and SFZ addons are the same.

![123](https://user-images.githubusercontent.com/51376332/64465203-f49ca080-d113-11e9-9f42-e9e00819abaa.png)

**Comment by kramola-RU** [comment]
I have a lot of files that I save using SF, in which the button works correctly.
For example:
[SF.zip](https://github.com/gildas-lormeau/SingleFileZ/files/3586023/SF.zip)

**Comment by gildas-lormeau** [comment]
Thanks for the zip file. This shows the behavior of SingleFile was buggy when you saved the page. I don't remember exactly when I fixed this bug but I confirm the 2 links "Отправлено" should not contain the URL to the website but should instead allow to navigate to the top of each post (on mobile for example). This feature has been requested and is especially useful for table of contents, indexes, etc.

**Comment by kramola-RU** [comment]
> especially useful for table of contents

understand

But it is inconvenient for me.
May be add an checkbox to settings?

**Comment by gildas-lormeau** [comment]
What would be the name of this setting?

**Comment by kramola-RU** [comment]
sorry, my english is not so good for that

I'm thinking about something like this:

1. Manage all internal links as external hyperlinks
2. Convert all internal links to external hyperlinks
3. Save all internal links as external hyperlinks

Default value = off
Comment: not recommended to use.  Navigation through the current page by clicking links will be unavailable.

**Comment by gildas-lormeau** [comment]
Thank you. Currently, I decided to add the option but it's hidden. It means you have to export your settings, open the file in a text editor, replace `resolveFragmentIdentifierURLs: false` with `resolveFragmentIdentifierURLs: true`, save the changes, and import the file in SingleFile.

**Comment by kramola-RU** [comment]
Thank you very much!
This decision is quite suitable for me.

**Comment by gildas-lormeau** [comment]
Great, so I'm closing the issue.
