### ISSUE TITLE
[Feature Request] Enhanced Naming

### ISSUE THREAD

**Issue by alivefromupstairs** [gildas-lormeau/SingleFileZ#23]
- Ability to change replacing invalid chars with underscore (to hyphen for instance.)
- Ability to format names to different cases. lower case/ upper/ title/ sentence/ kebab (which what I want)/etc.
- Regular expression matches. ex: remove every occurrence of " - " or replace it with " • ".
Also, some of the invalid chars are perfectly fine in Linux, and so, it would be unnecessary to transform them.

**Comment by gildas-lormeau** [comment]
>     * Ability to change replacing invalid chars with underscore (to hyphen for instance.)
It's possible via a hidden setting. To change it, export the settings from the options page. Edit the json file in a text editor, search `filenameReplacementCharacter` and replace the string after `:` (i.e. `"_"`) and import the modified file.
 
>     * Ability to format names to different cases. lower case/ upper/ title/ sentence/ kebab (which what I want)/etc.
> 
>     * Regular expression matches. ex: remove every occurrence of " - " or replace it with " • ".
These 2 features requires to embed an interpreter which would be much more sophisticated than the current implementation. There's also a risk it would have an impact on the syntax. I cannot guarantee I will add these features.

>       Also, some of the invalid chars are perfectly fine in Linux, and so, it would be unnecessary to transform them.
I added a hidden setting `filenameReplacedCharacters` (cf. commit above) for this. It will be available in the next version.

**Comment by alivefromupstairs** [comment]
>These 2 features requires to embed an interpreter.

I didn't take a look at the syntax, but would it not be possible to return `string.replace(/([a-z])([A-Z])/g, '$1-$2').replace(/\s+/g, '-').toLowerCase()` instead of `string`?
also, could you reference where the code responsible f turning `{page-title}` to the actual page title? I want to implement the same functionality in a Figma plugin.

**Comment by gildas-lormeau** [comment]
Regarding the feature about the case formatting, it may indeed be simple to implement. It depends on the requirements... For example, should the formatting rule be applied to the filename extension or the directories in the generated filename?

The code that replaces '{page-title}' with the title of the page can be found here.
https://github.com/gildas-lormeau/SingleFileZ/blob/9acc1e6db8c5a2bf17728c4915df689b86183665/lib/single-file/single-file-core.js#L1313-L1313

**Comment by gildas-lormeau** [comment]
@alivefromupstairs Here is a new feature that could interest you: https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved. This feature would allow you, for example, to change the title of the page just before saving the page.

**Comment by gildas-lormeau** [comment]
I'm closing this issue because it's fixed with user scripts support. Here is below a (simple) example of script that transform the title to a kebab-case value.

```
// ==UserScript==
// @name         Convert title to kebab style
// @namespace    https://github.com/gildas-lormeau/SingleFile
// @version      1.0
// @description  [SingleFileZ] Convert title to kebab style
// @author       Gildas Lormeau
// @match        *://*/*
// @noframes
// @grant        none
// ==/UserScript==


(() => {

  let title;
  dispatchEvent(new CustomEvent("single-filez-user-script-init"));

  addEventListener("single-filez-on-before-capture-request", () => {
    title = document.title;
    document.title = document.title.replace(/[^a-z0-9-\s]/gi, "").replace(/[- ]+/g, "-").toLowerCase();
  });

  addEventListener("single-filez-on-after-capture-request", () => {
    document.title = title;
  });

})();
```
