### ISSUE TITLE
Pages being saved as .txt

### ISSUE THREAD

**Issue by jajajaime** [gildas-lormeau/SingleFileZ#25]
I'm not sure if I'm missing something, but right after installing the extension I saved a couple of webpages to test it, from GitHub and Hacker News, and both saved as .txt. I don't see anything in the settings that would do this, and the filename is set to .html.
The .txt file opens on the browser as .txt, and upon changing the .txt to .html, it opens the saved page correctly.

**Comment by gildas-lormeau** [comment]
It's a rare bug in Chrome. Unfortunately, I was not able to reproduce it so I did not report it on https://bugs.chromium.org yet. I think the only way to fix this issue is to reinstall Chrome.

**Comment by gildas-lormeau** [comment]
It's a regression in Chrome. I can reproduce the issue (actually). I'm going to report it on https://bugs.chromium.org.

**Comment by gildas-lormeau** [comment]
I'm unable to create the issue right now because the server returns an error 400. I'll try a bit later.

**Comment by jajajaime** [comment]
I also upgraded to the latest version of Chrome, but still experiencing the issue. Thanks for looking over this!

**Comment by gildas-lormeau** [comment]
I confirm the issue can also be reproduced in Canary (Chrome 80). Curiously, SingleFile does not suffer from this issue...

**Comment by gildas-lormeau** [comment]
@jajajaime I just published a new version that allows to circumvent this issue by unchecking the new option "Misc > save pages in background". It should be available on the store in less than 7 days. Meanwhile, you can install the extension manually.

**Comment by gildas-lormeau** [comment]
@jajajaime I was finally able to identify the cause of the issue. It's fixed in the version 0.2.67 which will be available someday on the store of Chrome. Right now, I have to wait for the previous version to be reviewed before being able to upload the new one.

**Comment by jajajaime** [comment]
Thanks! I am now on 0.2.69 and pages save as .html.
