### ISSUE TITLE
imgur posts with multiple images are not saved

### ISSUE THREAD

**Issue by AdKiller** [gildas-lormeau/SingleFileZ#29]
example: https://imgur.com/gallery/QUiqfyx

SingleFilez v0.3.12

**Comment by gildas-lormeau** [comment]
I cannot really fix that bug. This website makes some significant efforts to remove images from the page when you scroll down or up. The only way I know to circumvent this issue is to zoom out the page before saving it to make sure all the images are simultaneously displayed.
