### ISSUE TITLE
Metadata in outside html

### ISSUE THREAD

**Issue by GarrisonBaird** [gildas-lormeau/SingleFileZ#30]
I wish the metadata (url, date, info) can be put in the outside html file, so that it can be read, edited by machine and/or human without decompressing and/or recompressing the zip
> Thanks and happy new year!

**Comment by gildas-lormeau** [comment]
I would need to find a format to store these data. Maybe a JSON format inspired from the RDF format of the metadata file in MAFF files?

**Comment by GarrisonBaird** [comment]
Yes JSON is the best, XML can be a secondary option, any machine and human readable format should be fine

**Comment by gildas-lormeau** [comment]
I think I'll implement a JSON file named `index.json` containing the following properties:
 - `originalUrl`: The original URL the page was saved from
 - `title`: The title of the page, if present
 - `archiveTime`: The date and time of the save operation
 - `indexFilename`: The file name of the main document

**Comment by gildas-lormeau** [comment]
I do not really understand the propositions. In your first solution, is the meta-data file stored in the zip file (e.g. in the root folder) and each zip contains only one saved page?

**Comment by GarrisonBaird** [comment]
- SingleFileZ.html
  - `<html>`...
  - **metadata**
  - js
  - zip data
  - ...`</html>`
---
- SingleFileZ.html
  - ...
  - zip data
    - index.html
    - ...
    - **metadata.json**
---
Hope this can make it clear :)

**Comment by gildas-lormeau** [comment]
Thanks for the clarification, I'll implement the second proposition I think.

**Comment by gildas-lormeau** [comment]
The feature has been implemented in the version 0.5.7 which is available for download on the store of Mozilla. It should be available for download on the store of Google in approximately 10 days.
