### ISSUE TITLE
Clarification re: Help on Form Buttons - synchronize options

### ISSUE THREAD

**Issue by JBigglesworth** [gildas-lormeau/SingleFileZ#35]
Could you expand the Help re 'Syncrhonize Options' please?

**Form buttons
    synchronize options
    Check this option to synchronize your options with the account associated to your browser session.**

I believe 'options' refers to the config settings within SingleFileZ but I do not understand what "account ... browser session" means and what the relevance/significance of syncing between these is all about.

**Comment by gildas-lormeau** [comment]
In Chrome and Firefox, you can login in your browser with your Gmail and Mozilla account respectively. If you're logged in, then you can save your options/settings into the cloud and retrieve it automatically when this option is checked.

**Comment by JBigglesworth** [comment]
Thanks, I now understand the 'synchronize' option enables SingleFileZ config to be synchronized across multiple Firefox (or Chrome) installations that have been linked by a Mozilla (or Gmail) account.  (The Help description seemed to convey something different.)

**Comment by gildas-lormeau** [comment]
Sharing the same options between multiple browser instances is indeed a use case. Another one is saving/restoring your options. I agree the help page is not 100% clear even though I think its' accurate. I'll try to make things clearer.

**Comment by gildas-lormeau** [comment]
I rephrased the description as:
`Check this option to synchronize your options and make them available in all instances of the browser you are logged into, on different devices.`
