### ISSUE TITLE
Truncated filenames.

### ISSUE THREAD

**Issue by ghastlyman** [gildas-lormeau/SingleFileZ#38]
I've only just begun using this add-on.
I find some files are saved ok (ie, can be opened) but the filename is truncated to a single letter, eg, "This is a web page.html" would be truncated to "T", with no extension. I'm assuming there's a bug in the code that handles filename templates. Image of my filename template attached.

Will submit a more thorough bug report if needed.
Cheers.

![1  Config pt1of3](https://user-images.githubusercontent.com/61773107/75851174-e5f02700-5de0-11ea-923d-4e26f455cb2f.png)

**Comment by gildas-lormeau** [comment]
That's weird.  Could you please export your settings, open the file in a text editor, and confirm that in the JSON file the property `filenameMaxLength` is set to a value superior to `1` (it is `192` by default)?

**Comment by ghastlyman** [comment]
> 
> 
> That's weird. Could you please export your settings, open the file in a text editor, and confirm that in the JSON file the property `filenameMaxLength` is set to a value superior to `1` (it is `192` by default)?

Confirmed (192 chars).

**Comment by gildas-lormeau** [comment]
Could you please post your exported settings? It would maybe help me to reproduce the issue.

**Comment by ghastlyman** [comment]
Settings file attached.
I still get the bug about 20% of the time. Will completely reinstall browser tomorrow and test with other add-ons disabled (in case of accumulated FF gremlins).
[singlefilez-settings.txt](https://github.com/gildas-lormeau/SingleFileZ/files/4303466/singlefilez-settings.txt)

**Comment by gildas-lormeau** [comment]
Thank you. Do you mean that if you save the same page 5 times, the bug will occur only one time?

**Comment by gildas-lormeau** [comment]
I saved a dozen of pages with your settings and was not able to reproduce the issue. I have 2 other questions:
- What is the full path of your download folder or how many characters does it have? e.g. the length of "C:\Users\Gildas\Downloads"
- Is the filename already truncated in the "Save as" dialog?

**Comment by ghastlyman** [comment]
> 
> 
> Thank you. Do you mean that if you save the same page 5 times, the bug will occur only one time?

No, I meant every once in a while, a filename gets truncated. I can't see a pattern.

**Comment by ghastlyman** [comment]
> 
> 
>     * What is the full path of your download folder or how many characters does it have? e.g. the length of "C:\Users\Gildas\Downloads". Does it contain special characters?
I rarely save to Downloads folder.
I never use special chars in directory names. The pathnames are a bit long, but no excessively. See pics in next message.
> 
>     * Is the filename already truncated in the "Save as" dialog?
No, filenames look good in Save As dialog. But they're truncated in File browser, and when browsing directory in terminal app.

**Comment by ghastlyman** [comment]
Something weirder going on.

I created this directory yesterday (image 1), and stored three files there. Each had filename truncated.

![img-1](https://user-images.githubusercontent.com/61773107/76168336-eb45cc80-6166-11ea-9d16-1333470e7915.png)

Now, I know that file "E" is the webpage [https://emys.co/]. I can verify that by opening "E" in FF, and using your infobar. So what happens if I try to save that same webpage into that same directory? You'll never guess.

Image 2 is the Save As dialog box for your add-on, just prior to hitting the Save button. (Notice your add-on didn't pick up the h1 heading. Is that significant?)

![img-2](https://user-images.githubusercontent.com/61773107/76168354-13353000-6167-11ea-9469-c4f8d86d1e2c.png)

Image 3 is from just after having hit the Save button. Wtf? Windows knows those files are the same, even though the filenames are completely different.

![img-3](https://user-images.githubusercontent.com/61773107/76168359-1e885b80-6167-11ea-8717-aa0e7b75b468.png)

I click Yes to see what happens. No complaints. But when I look at the directory again, well, you'll never guess. The "N" file has been replaced! (Image 4).

![img-4](https://user-images.githubusercontent.com/61773107/76168364-2a741d80-6167-11ea-8a73-5612119c860e.png)

It's nearly 5am, so maybe I'm missing something obvious?

**Comment by gildas-lormeau** [comment]
It looks like you're having issues with the maximum filename length. The last issue is kind weird indeed, I think this is probably a bug in Firefox. If you follow the procedure described here: https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/, what is the value of "LongPathsEnabled"? On my brand new PC, the value is "0" (disabled). I'm wondering if enabling it would change anything.

I think you should maybe reduce the value of the `filenameMaxLength` in your settings.

**Comment by gildas-lormeau** [comment]
@ghastlyman any news?

**Comment by ghastlyman** [comment]
Hi Gildas.
I reinstalled Firefox from scratch, installing only a minimal set of add-ons (Ublock Origin, Https Everywhere, etc).
This did not solve the problem of truncated filenames.
I've since abandoned SingleFileZ, and moved to SingleFile, saving downloads to the Win 10 Download folder only.
No more problems!
Steve.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by gildas-lormeau** [comment]
Thanks @ghastlyman. I'm glad to hear you found a way to fix this issue :)
