### ISSUE TITLE
UI suggestions for Options page.

### ISSUE THREAD

**Issue by ghastlyman** [gildas-lormeau/SingleFileZ#39]
1. The *Import*, *Export*, and *Reset* buttons should be renamed *Import Settings*, *Export Settings*, and *Reset Settings* respectively.
1. At a glance, the meanings of the greyed-out *Default settings* drop-down menu, and the *"+"*, greyed-out *"-"*, and greyed-out *pencil* icons, isn't clear. The tooltips help, but only if you think to check for them. There must be a better way to make this functionality clear at a glance.
1. The *Synchronise options* checkbox begs the question, of the casual observer: *Synchronise with what?*

**Comment by gildas-lormeau** [comment]
1. It's subjective, from my point of view.
2. It's not easy on small screen. I agree that I'm not a designer and there must be a better way to do it.
3. It's written in the help page. Since a lot of people don't want to read it, I might add a "?" icon to fix that as usual.

**Comment by gildas-lormeau** [comment]
Issues are not write-only. I'm closing it because I didn't get any feedback.
