### ISSUE TITLE
Add option to render custom file extension

### ISSUE THREAD

**Issue by lumnikemel** [gildas-lormeau/SingleFileZ#40]
I use both SingleFile (SF) and SingleFileZ (SFZ). I keep both, because my indexing app can't render an SFZ file (it shows me highlights of the found words), but can with SF files. However, I want to be able to keep the internal page resources that SFZ provides.

I set SFZ to save pages with the extension "htmlz", but if I open a page with this extension it doesn't render, and have to rename to "html". Would it be possible to get an option to customize the extensions that SF/SFZ will try to render?

**Comment by gildas-lormeau** [comment]
It looks like this issue is specific to Chomium-based browsers. I think I should be able to make it work without any option. Note that Firefox can open htmlz files though.

**Comment by gildas-lormeau** [comment]
I implemented the feature. It works with any custom filename extension. I hope the version implementing this feature will be published next week.

**Comment by lumnikemel** [comment]
Wow, that was fast. Thanks. I'll let you know how it works.
