### ISSUE TITLE
Folder in file name template is not working

### ISSUE THREAD

**Issue by sebyao5510** [gildas-lormeau/SingleFileZ#43]
The folder delimiter / is converted to _. I tried with multiple options like \/ and // etc, but still no luck. The files are stored with a prefix of ARCHIVES_ instead of in the ARCHIVES sub-folder of my downloads folder.
![image](https://user-images.githubusercontent.com/33173986/77504312-019d9900-6e86-11ea-81eb-2c445f0d0c51.png)

![image](https://user-images.githubusercontent.com/33173986/77504385-2eea4700-6e86-11ea-8f6e-3db5e84f3c08.png)

**Comment by gildas-lormeau** [comment]
Is the option "Misc > save pages in background" enabled?

**Comment by sebyao5510** [comment]
It was disabled as the files were getting saved in the Downloads folder with funny names like "73ba8ef8-23bf-4768-99c1-027fc78c1c9c.htm". Disabling it providespropernames based on the template set in options except for the folder.
![image](https://user-images.githubusercontent.com/33173986/77879629-7141c880-7278-11ea-8631-65581c3e246e.png)
![image](https://user-images.githubusercontent.com/33173986/77879655-80c11180-7278-11ea-849a-122e263e7938.png)

**Comment by gildas-lormeau** [comment]
The filename issue is a bug in Chrome documented in the [known issues](https://github.com/gildas-lormeau/SingleFile#known-issues). The only reliable way I know to get rid of it is to reinstall Chrome.

**Comment by sebyao5510** [comment]
I will try that, but later, and update whether it worked for me. Thanks.

**Comment by gildas-lormeau** [comment]
@sebyao5510 Were you able to circumvent of fix this issue?
