### ISSUE TITLE
JS file can't decode Chinese

### ISSUE THREAD

**Issue by Red-Flame** [gildas-lormeau/SingleFileZ#44]
When I save the Chinese page,I found that the js file can't decode Chinese,such as this url 
"http://www.chinanews.com/qxcz/news/2010/01-16/2076009.shtml".

  This js file "http://www.chinanews.com/javascript/cnsurl-2008.js" should be `...document.writeln('<a target="_blank" href="http://www.chinanews.com/">首页</a>|<a target="_blank" href="http://news.chinanews.com/">新闻...`,but the saved js file is `...document.writeln('<a target="_blank" href="http://www.chinanews.com/">��ҳ</a>|<a target="_blank" href="http://news.chinanews.com/">����...` 
Thanks!

**Comment by gildas-lormeau** [comment]
Thank you for having reported this issue, I was available to reproduce it it. This issue is fixed in the version 0.5.38.
