### ISSUE TITLE
Issue of archive "dynamic" webpage

### ISSUE THREAD

**Issue by Rupthya** [gildas-lormeau/SingleFileZ#46]
Sorry due to lack of programming knowledge, i am not able to search the solution well and think this is a properly title to describe my questions.

Here is a sample: 
https://www.jp.square-enix.com/seiken3_tom/character/

This page stuck at loading circle with [Wayback Machine](http://web.archive.org/)

Using SingleFileZ to archive it, as result i am not able to click the "link" to pop up the character page,

is there any settings change to solve the problem?

Thank you.

**Comment by gildas-lormeau** [comment]
Disabling the option "Other resources > remove scripts" can sometimes do the trick. For this particular site, it should work. SingleFile can save the dynamic behavior of the page when doing so but there's an issue with SingleFileZ when it tries to load the scripts. 
Although, it will work if you unzip the page saved with SingleFileZ and open the index.html file.

This is definitely a bug in SingleFileZ. I'll try to see what's wrong.

**Comment by gildas-lormeau** [comment]
I was able to (finally) fix this issue. The fix will be available in the next version of SingleFile and SingleFileZ.
