### ISSUE TITLE
Suggestion: MAFF File Format

### ISSUE THREAD

**Issue by frank334** [gildas-lormeau/SingleFileZ#47]
You should consider to use the MAFF File format for archiving web pages.

[https://en.wikipedia.org/wiki/Mozilla_Archive_Format]

For classic Firefox versions, the latest versions can be downloaded here (see sourcecode by unzipping the XPI files)

https://addons.thunderbird.net/en-us/thunderbird/addon/mozilla-archive-format/versions/?page=1#version-5.2.1

further Infos:

http://maf.mozdev.org/maff-file-format.html
https://github.com/danny0838/webscrapbook
https://pypi.org/project/webscrapbook/
https://addons.palemoon.org/addon/mozarchiver/

I use this extension quite often to save important information material during research. Fortunately I still have the saved pages, because often they just disappear from the network. Sometimes really valuable information.

I was deeply dissappointed by the stupid Mozilla developers to cripple the extension API (XUL) without alternatives giving the same features. So the MAFF developer had to give up. MAFF was nicely integrated in the GUI, right in the save page dialog, as another format choice. So you can also choose the directory. SingleFile is not as comfortable to use.

The file format question is really important. It shouldn't be a hack, such as base64-coding of images in HTML code.

Traditionally we had the MHT MHTML file format, introduced by Internet Explorer decades ago. It was also the reason for me to switch from Netscape to IE. MHTML is a standard, also used for transmitting Email with HTML and embedded media.

Unfortunately MHTML is not an efficient coding, using ASCII instead of binary content. It's not compressed and wastes a lot of space, especially if you save a lot of documents during research.

MAFF is a much better choice. It's a compressed ZIP of all page contents, HTML and enbedded elements like CSS, JS, Images etc. Similar to the modern way of saving Office documents, a ZIP of text and contents as files.

This handling has many benefits. You can just extract elements like Pictures from the ZIP. It's simple to process such documents (batch processing, automated extraction, indexing, converting to other formats).

You don't have this flexibility with the SingleFile format, where binary elements are ASCII-coded into HTML-Source.

SingleFileZ might be better, but still it's a HTML file and not a compatible ZIP. You can't use ZIP tools to extract contents from the SingleFileZ HTML page.

Of course you need an extension to read ZIP based file formats in a browser. But it's the clean way of defining document formats. Self-extracting code within the document itself is not the elegant way of a file format. What if it  should be used in another context, say Office suites that are not compatible with the Browser Javascript?

Maybe the self-extractor could just be an option, like with self-extracting ZIPs. They are used sometimes, but normal ZIPs are most common. I'm also very sceptical with self-extracting code because it could hide malware, especially from unknown sources.

When exchanging documents with unkown partners, active code should be avoided. I usually switch off Macros in Office documents. My Browser has the Noscript default. It is an important security aspect (maybe the reason I never got a virus, mostly distributed by code within documents).

**Comment by gildas-lormeau** [comment]
> SingleFileZ might be better, but still it's a HTML file and not a compatible ZIP. You can't use ZIP tools to extract contents from the SingleFileZ HTML page.

I'm sorry but that sentence is wrong. SingleFileZ produces 100% valid zip files that follow the specification. Any software that pretends to follow the specification should be able to open files produced by SingleFileZ. If it cannot then it's a bug or a limitation of the software. For example, [this video](https://www.youtube.com/watch?v=RJWhDmYhnX4) shows that the command tool "zip" can update files produced by SingleFileZ without any particular issue.

The reason SingleFileZ produces HTML files instead of MAFF files is the reason why the extension exists actually. Today, it's **technically impossible** to write an extension that would allow you, for example, to drag and drop a MAFF file in the browser, or to double-click on it from the filesystem to open it in the browser. 

Note that's also why SingleFile exists. It was created 10 years ago for Chrome because it was also technically impossible to support other formats like MHTML or MAFF. The innovation of SingleFile was to use the HTML format (and data URIs) instead. Meanwhile Google added the support of MHTML in Chrome though.

**Comment by frank334** [comment]
No, technically it's not a ZIP, it's more a dirty hack that just works with the current ZIP programs

A valid ZIP starts with the magic bytes:

PK\x03\x04 

But these files start with

"<!DOCTYPE html> <html data-sfz..."

And so these are HTML document types. The ZIP packer just reads along the corrupt header until it finds the real ZIP header. This might work, or not, ...

Sometimes you need some dirty hacks to get software running. But it's a bad idea to base a document standard on dirty hacks. It's not only important hat those docs can be read today, but forever as an archive. Saving Web documents to me means to archive important information. Some of my historic docs are 20 years old in my archive. Also for PDF you excpect a well-defined standard for archival purpose.

I know, after Mozilla destroyed the most important Addon API interfaces we have a dilemma. But it's more important to fix Mozilla than to devastate well-defined document standards.

MAFF is a really good approach. It keeps the document structure. File names of embedded objects are kept intact. The document structure is similar to other office documents (MS-Office, LibreOffice).

**Comment by frank334** [comment]
Maybe we could ask Mozilla to introduce minimal API support for such purposes. Firefox had the ability before. In my current classic Firefox (56.x version) I can open or drop MAFF docs in the browser. Also Waterfox and Palemoon have support. 

MHTML is supported very widely. It was the reason for me, almost 20 years ago, to switch from Netscape to Internet Explorer. I don't understand why Mozilla is so lazy in respecting document standards. We have to fix Firefox, not the standards.

**Comment by frank334** [comment]
Is it really technical impossible for latest Firefox-versions to open a binary ZIP? I used the feature the last 10 years or so, almost daily with archived documents. Without extension, Firefox can't handle the MAFF documents. But with MAFF installed, they are interpreted correctly.

What about moving the ZIP-reading HTML/Javascrip code to the Extension, to inject it at page load? Of cource, the .maff oder .htmlzip extension has to be associated with Firefox to be able to open the doc.

The idea itself is good to create a ZIP-based document standard for Web-pages. MHTML is the known standard for this purpose, but unfortunately it wastes too much space without compression.

If Firefox is broken or unable to handle it, we should fix Firefox and not introduce bug-fixing code in every document we save.

Documents with active content (Office Macros, Javascript) are always a bad idea and a huge security hole. Almost all malware was distributed by infected Office and PDF documents in the recent past.

So, disable Scripting is the default-recommendation for documents formats (Switch Javascript off in PDF-reader, Switch Macros off in Office, and Javascript off for Webfiles) ...

**Comment by gildas-lormeau** [comment]
> No, technically it's not a ZIP, it's more a dirty hack that just works with the current ZIP programs

These are valid zip files. They're using a *feature* of the zip specification allowing the compressed entries to be stored anywhere in the file. This feature is available via the standard field "relative offset of local header", cf. 4.3.12 [here](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT). This feature is not a hack at all.

> And so these are HTML document types. The ZIP packer just reads along the corrupt header until it finds the real ZIP header. This might work, or not, ...

This is not how unpackers work. I know that because I wrote [zip.js](https://github.com/gildas-lormeau/zip.js). Unpackers search the "end of central directory record" in the zip file (cf part 4.3), then they can determine where each "local file header" are located in the file. Actually, unpackers read first the end of a zip file in order to uncompress it. AFAIK, This algorithm is reliable and works well. Unpackers that don't implement this algorithm don't follow the specification and are using hacks.

> MAFF is a really good approach. It keeps the document structure. File names of embedded objects are kept intact. The document structure is similar to other office documents (MS-Office, LibreOffice).

I'm sorry if you consider SingleFileZ is not using the good approach even though it produces valid zip files conformant with the "elementary" level of the MAFF [spec](http://maf.mozdev.org/maff-specification.html). Note that original URLs of all the resources can be found in the `index.json` file stored into the zip.

> Maybe we could ask Mozilla to introduce minimal API support for such purposes.

There's already an issue for this on bugzilla, see here: https://bugzilla.mozilla.org/show_bug.cgi?id=1457500

> Is it really technical impossible for latest Firefox-versions to open a binary ZIP?

Yes it is. Drag and drop a zip in your browser, do the test, Firefox (or Chrome) will "download" it.

What about simply replacing in your settings the template of the filename with `{page-title} ({date-iso} {time-locale}).maff` or `{page-title} ({date-iso} {time-locale}).zip`? This would automatically and easily disable the self extracting script.

**Comment by frank334** [comment]
Oh, I didn't know that the PK\x03\x04 header magic was optional. Yes, it makes sense to attach the directory info at the end. But how should the file type be detected? In Linux file types are distiguished by the header magic values. I never saw ZIP files without the PK magic.

It's also important for indexing software like Docfetcher to be able to detect the document type. It has the "<!DOCTYPE html>" document type and therefore will be treated just as HTML without seeing the binary blobs inside.

I'm not happy with the fact that a document uses self-executing code for opening. This is a big security problem, just as with Javascript in PDF and Basic-Macros in Office documents.

However, the Idea of using ZIP is a very good choice to save Web pages,  much better than MHTML.

Why not full MAFF compatibility of the embedded ZIP? When I rename it to .maff it can't be opened with the MAFF extension of PaleMoon.

Sometimes Pages have interesting embedded objects, like large number of photos of a gallery or subframes. Then it's nice to open the ZIP and extract some of them. Or just open the ZIP to delete some junk of large docs. In MAFF you see the orignal filename and that's more comfortable to manage than just sequence numbers. For the machine it doesn't matter, just for humans that want to work with the contents.

Another difference: when you open HTML source code view you see the original page in MAFF, along with a reference to the original URL. In SingleFileZ you just see the self-extracting header with a lot of binary stuff, but not the orignal page source.

I know Firefox won't open ZIP types. But what if you create a special Mime-Type like MAFF and associate that type with Firefox (from OS or within the Firefox document type list)? Maybe even cheat and declare it as HTML. And while opening the page, the WebExtension injects code for the ZIP-extraction. A bit similar to your solution, not self-executable but let the browser do the extraction itself. Like with MAFF.

The SingleFileZ solution is much closer to MAFF than any other Webextension. So maybe there is a chance to make it fully MAFF compliant and secure without self-extracting active elements inside.

**Comment by gildas-lormeau** [comment]
To summarize, you want SingleFileZ to produce zip files that are not self-extracting but could still be displayed in a browser if SingleFileZ is installed. I'm not sure that this is technically possible. If it is possible, I consider that implementing this feature is a hack to get around the lack of API in extensions to declare that they support a given mime-type. At first glance, this hack would work in Firefox but the user experience will not be pleasant as it will see the binary content in the browser for a certain amount of time.

I'm surprised Palemoon refuses to open files saved with SingleFileZ whereas these files conform the the "Elementary" level in the MAFF specification. I did a test in webscrapbook and it worked as expected.

**Comment by frank334** [comment]
But how to detect the type? If it gets a File with .html extension and textual HTML header I would also detect it as HTML mime type. Why should it look at the file end signature? SignleFileZ documents are only detected because embedded Javascript will execute and unpack the embedded ZIP. If it's really a different document type it needs kind of a simple signature for mime type detection or a different extension. XPI extensions also are of ZIP type. I think it's not a problem that people would get irritated by binary content if it's a different extension type like .maff. Those documents are usualle not put on web servers, just for personal archive collections.

Also search engines have to differentiate. They dont run Javascript while indexing. My .maffs get indexed with Docfetcher by interpreting the .maff extension as ZIP type.

**Comment by gildas-lormeau** [comment]
Indeed, that would be complicated to detect that the zip file the user opened is a valid zip file and this file is in fact a file saved with SingleFileZ. I don't think I will try to implement a way to autodetect such files. It means that you would need to unzip files in order to open them in a browser.

If you want to index the text of the page without unzipping the file, there is already an option for that, see HTML content > make text searchable.

**Comment by gildas-lormeau** [comment]
@frank334 To sum up, do you think an option should be added to produce "pure" zip file instead of self-extracting files?

**Comment by frank334** [comment]
Yes, I think it is worth to keep the MAFF standard alive. This is a pure ZIP with the MAF extension. Think not only for the moment, but in decades. It's now almost 20 years that I'm saving MAFF from important docs. Many of them are not online any more, even some content even vanished from archive.org. It is important to have an archive format that you can rely on. Self-extracting HTML is a bit critical, will it work 20 years later, with later Javascript engines? Document-ZIPs, like OpenDocument, like MS-Office XML-Zipped-Docs are made for long-living document standards.

We desperately need reliable web archive standards. MHT is the first one and standardized. Unfortunately not compressed and wasting lots of space in document collections. HTML is not made for natively embedding binary content. So MAFF is the only reasonable standard we have. Not only for Mozilla Firefox, can be used also for Chrome and other browsers. SingleFileZ is a WebExtension. So it might be possible to port it to Chrome, too.

At the moment, the MAFF file type is associated with an older browser with the MAFF extension. So I can still use my documents. I don't know if I will stay with Firefox. They force very ugly GUIs, remove APIs, now using a very idiotic zoom-effekt in the URL bar ....

Maybe in the long-term we should move to a better Firefox fork, like Pale-Moon or Waterfox.

Meanwhile I'm using the WebScrapBook Extension to create MAFF for saved pages. I'm not really happy with it, because the file names are generic and meaningless.

I'm really missing the comfortable Save-As Dialog from the original MAFF extension.

It would be great if it can be restored somehow.

**Comment by frank334** [comment]
Btw, from the standards perspective:
- I don't know if it conform not to start a ZIP with the typical ZIP magic bytes in the beginning, relying on the backwards-reading.
- At least there is a second problem that the HTML cannot be standard-conform:
With
<![CDATA
you can indeed start a binary-blob, like PKzip content.
BUT: such a ZIP cannot guarantee that it does not contain binary bytes equal to the CDATA closing tags. According to the HTML standard, after a CDATA closing tag, further HTML code could follow. It would be indistinguishable if the CDATA closing tags are really ending the binary blob or if they are part of the binary blob itself. So the blob has to guarantee that this byte sequence will never be part of the binary data. That's impossible to guarantee and not ZIP-conform.

It think it's more luck that it works, but not guaranteed to work according to the standards.

A pure ZIP would be well defined.

Ok, I understand the restrictions of newer Firefox extension API that a binary MAFF/ZIP type can't be auto-opened. So, the self-extracting HTML is more an interim solution or work-around to a deficient Firefox Extension API.

**Comment by cy7yz2rj** [comment]
> Meanwhile I'm using the WebScrapBook Extension to create MAFF for saved pages. I'm not really happy with it, because the file names are generic and meaningless.

Sorry for O/T but WebScrapBook can capture pages like MAFF and SingleFile, without adding them to the scrapbook itself. When not using using the scrapbook, filenames can be configured using templates in the extension options page.


> To sum up, do you think an option should be added to produce "pure" zip file instead of self-extracting files?

I'd very much welcome a strict [MAFF spec compliant](http://maf.mozdev.org/maff-specification.html) option, especially if it took care of [request 2 in this list](https://github.com/danny0838/webscrapbook/issues/30), which SingleFileZ is already very close to doing.

While not mandatory by the MAFF spec, index.html and index.rdf being the only files below the top-level folder of each captured page, with everything else tucked away in a sub-directory, is a huge usability improvement.

I suppose the WS implementation does conform to the spec but that project focus is to be a ScrapBook replacement, not a MAF one, it's understandable they won't bother to change how it currently works.

**Comment by gildas-lormeau** [comment]
> I'd very much welcome a strict [MAFF spec compliant](http://maf.mozdev.org/maff-specification.html) option, especially if it took care of [request 2 in this list](https://github.com/danny0838/webscrapbook/issues/30), which SingleFileZ is already very close to doing.
> 

Today, SingleFileZ cannot save multiple pages in the same zip file. So, what is the point to have a sub-directory like `TIMESTAMP` when the zip file contains only one page?

**Comment by cy7yz2rj** [comment]
Extracting a single captured page creates multiple files and directories in the extraction folder, and extracting multiple captures leads to collisions.

Having a single, uniquely named directory (I assume MAF uses `UNIX timestamp_###`, WS uses `YYYYMMDDHHmmss###`) in the root of the zip file prevents that: each capture lands in its own folder, with the timestamp acting as sorting mechanism.

As with WS, it's fair to consider this being out of scope for SFZ.

**Comment by gildas-lormeau** [comment]
I could add an option for this even though I think this issue is more related to the zip tool used to unzip pages than SFZ. Strangely, the MAFF spec does not impose or suggest any format for the name of that sub-directory. Maybe I'm wrong but, as far I know the format, you're proposing is not a [UNIX timestamp](https://www.unixtimestamp.com/)_###. Moreover, this format does not guarantee the folder name will be unique if you exchange files with other people. Handling the ### part is not necessarily trivial in SFZ.

**Comment by cy7yz2rj** [comment]
You're not wrong, it seems to be UNIX timestamp + 3 digits (msecs?) + underscore + some more digits (just found an example with only 2 at the end instead of 3).

You're also right that's it's not an SFZ issue, it's my personal preference; others may prefer that SFZ has no top directory at all. Don't waste time on it if it's a lot of work and it seems like the target audience is 1.

I personally don't care if it's not unique enough for sharing with others as long as it doesn't collide locally and it's unambiguously sortable by my file manager in such a way that the higher up when alphabetically sorting the earlier the capture.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback. Note that `YYYYMMDDHHmmss` is not a timestamp at all, a UNIX timestamp is the number of seconds since Jan 01 1970 (UTC).

**Comment by cy7yz2rj** [comment]
The UNIX timestamp is only used in [MAF](http://maf.mozdev.org/) (the extension) captures; `YYYYMMDDHHmmss` is for [WebScrapbook](https://addons.mozilla.org/en-US/firefox/addon/webscrapbook/) captures.
The 2 addons use different naming conventions for the top level directories inside the .maff files.

**Comment by gildas-lormeau** [comment]
Ah! Thanks for the clarification.

**Comment by gildas-lormeau** [comment]
I added in the version  0.5.70 the 2 following options:
 - "ZIP content > create self extracting archives"
 - "ZIP content > create a root directory"

I think that's all I can do to fix this issue.

**Comment by gildas-lormeau** [comment]
I closed the issue but we can continue to discuss about the features.
