### ISSUE TITLE
No javascript saved?

### ISSUE THREAD

**Issue by BarbzYHOOL** [gildas-lormeau/SingleFileZ#5]
I tried the iframe example and when I click on the tab "CSS" on that page, it doesn't show up, as if the javascript didn't work.

Normal? my issue is saving javascript on these pages, can't find a proper solution

**Comment by gildas-lormeau** [comment]
I noticed this too. This is indeed an issue. I'll fix it. Note that only scripts found in the DOM when you will click on the save button will be saved.

**Comment by gildas-lormeau** [comment]
It's fixed in the version 0.0.16 I just published. Feel free to re-open the issue if it's not working for you.

**Comment by BarbzYHOOL** [comment]
>  Note that only scripts found in the DOM when you will click on the save button will be saved.

What does it mean?

**Comment by BarbzYHOOL** [comment]
Hmm please update the example file :P

**Comment by gildas-lormeau** [comment]
> 
> 
> > Note that only scripts found in the DOM when you will click on the save button will be saved.
> 
> What does it mean?

It means for example that if a script downloads another script but does not insert any script tag into the page in order to execute it, or remove the script tag just after the execution, the latter script won't be saved.

**Comment by gildas-lormeau** [comment]
> 
> 
> Hmm please update the example file :P https://github.com/gildas-lormeau/SingleFileZ/tree/master/examples (i just retested them like an idiot)

The examples I provide do not include scripts because it's not really reliable for the reason I described in the previous answer. Also, I'm not sure it's very secure. 

To give you an idea, here are the 2 examples with the scripts included.
[examples.zip](https://github.com/gildas-lormeau/SingleFileZ/files/3204375/examples.zip)

**Comment by BarbzYHOOL** [comment]
Hehe cool, it's working but the CSS frame is empty now while it should display this, right ?

```
iframe {
    border: 1px solid black;
    width: 100%;
}

.output {
    background: #eee;
}
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe
