### ISSUE TITLE
Created file not opening with Chrome browser nor other chromium browsers

### ISSUE THREAD

**Issue by Rob-the-knob** [gildas-lormeau/SingleFileZ#53]
The Singlefilez file created in Opera with your extension opens flawlessly with Firefox but NOT with Chrome or with Opera itself.

The error message while trying to open the file in Opera or Chrome:

Error: Cannot open the page from the filesystem.
Chrome: Install SingleFileZ and enable the option "Allow access to file URLs" in the details page of the extension (chrome://extensions/?id=offkdfbbigofcgdokjemgjpdockaafjg). Otherwise, start the browser with the switch "--allow-file-access-from-files".
Safari: Select "Disable Local File Restrictions" in the "Develop" menu.

**Comment by gildas-lormeau** [comment]
This error message is displayed due to a technical limitation in Chrome-based browsers, such as Chrome, Opera, Microsoft Edge etc. This limitation prevents SingleFileZ from working properly in these browsers. There is nothing I can do to fix or circumvent this issue.

The only way to solve this problem is to remove SingleFileZ from the Chrome Store.

**Comment by Rob-the-knob** [comment]
Probably that would be the only solution to this problem.
Like said before your other extension Singlefile is outstanding.

**Comment by gildas-lormeau** [comment]
Does it really hurt that SingleFileZ is present of the store of Chrome? I force nobody to install it.

**Comment by Rob-the-knob** [comment]
No it probably doesn't hurt SingleFileZ is present on the store of Chrome but mentioning in the manual that created files are compatible only with Firefox would be appropriate if you ask me.

**Comment by gildas-lormeau** [comment]
The warning has been fixed for a long time actually.
