### ISSUE TITLE
"skip duplicates files" don't always work

### ISSUE THREAD

**Issue by TheFrenchGhosty** [gildas-lormeau/SingleFileZ#54]
Set "file name conflict resolution" to "skip duplicates files" doesn't always do what it's supposed to.

In website where the <title> is the same on multiples page it will handle it like if it's set to "create a unique file name". (example, my website homepage: https://pussthecat.org/ and the about page of website: https://pussthecat.org/about/ )

For some websites (no idea what's causing it) it will always handle it like if it's set to "create a unique file name" (example, my Bibliogram instance homepage https://bibliogram.pussthecat.org/ ).

(Note: I use my website because it's where it's consistent, feel free to use another website to try it)

**Comment by gildas-lormeau** [comment]
Do you confirm the file name template in your settings is `{page-title}.html`?

**Comment by TheFrenchGhosty** [comment]
The name template I use is ```aaaSingleFileZ/{year-utc}{month-utc}/{year-utc}{month-utc}{day-utc} - {page-title}.html```

After some more testing it doesn't seem consistent, however I am able to reproduce the issue every time if I restart the browser between two save.

- Open browser with SingleFileZ autosave enabled with these settings:

```
File name:

Template: aaaSingleFileZ/{year-utc}{month-utc}/{year-utc}{month-utc}{day-utc} - {page-title}.html

file name conflict resolution: skip duplicate file

HTML Content:

Tick "Remove frames"

Auto-Save

auto-save waiting delay after page load (s): 10 sec

Misc.

Tick "set maximum size for embedded ressources"

maximum size (MB): 50MB
```

- Go to a link (this one seems to be consistent https://terraria.gamepedia.com/Copper_Shortsword)

- Page saved

- Restart the browser

- Go to the same link

- Page will be saved again, name is handled the way "create a unique file name" handle it

**Comment by gildas-lormeau** [comment]
Actually, this issue is due to a limitation of the downloads API. This issue is documented in the help page though, i.e. "The "skip duplicate files" action only detects duplicates among files downloaded during the current browsing session."

**Comment by TheFrenchGhosty** [comment]
Oh interesting, this is a non-issue I guess then?

**Comment by gildas-lormeau** [comment]
Yes, currently it cannot be fixed.
