### ISSUE TITLE
www.consultant.ru -- stucks at step 3

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#62]
I`m trying to save the page:

http://www.consultant.ru/document/cons_doc_LAW_32449/f543fb6df93012a263898fd4f4085ed587c5f43f/

but gets stuck at step 3

Could you check this ?

**Comment by kramola-RU** [comment]
Great !
Thanks alot !

**Comment by gildas-lormeau** [comment]
Thanks also for having reported the issue. I'll publish the new version very soon.

**Comment by gildas-lormeau** [comment]
It's published. That should be fixed in the version 0.6.1.

**Comment by kramola-RU** [comment]
I have already tried version 0.6.2 :)
Works fine !
Thank you !

**Comment by gildas-lormeau** [comment]
You're welcome :)
