### ISSUE TITLE
"Save page with profile" feature not present in Chrome

### ISSUE THREAD

**Issue by redactedscribe** [gildas-lormeau/SingleFileZ#63]
Hello again Gildas,

Thanks for implementing the feature. An issue however: after installing SingleFileZ into the Brave browser (I can't test Chrome, but I assume it'd also be affected), I've noticed the option isn't even present in the context menu list. Perhaps I'm missing something, but even with your extension reset to default, the feature seems completely missing.

Whether SingleFile (non-Z) is affected, I don't know.

Thanks.

**Comment by gildas-lormeau** [comment]
It's working fine on my end. Please make sure your version of SingleFile is up to date (>= 1.18) and that you have at least 2 different profiles in your settings.

**Comment by redactedscribe** [comment]
Ah, yes. That makes sense. Not that there's a rush, but I'm curious: how long does it usually take before a Chrome Web Store extension is accepted?

**Comment by gildas-lormeau** [comment]
It really depends, it tends to change quite often. Today, for SingleFile it takes usually 1-2 days and maybe 4-5 days for SingleFileZ on the store of Google.
