### ISSUE TITLE
File name variables {url-href} seems broken

### ISSUE THREAD

**Issue by Rupthya** [gildas-lormeau/SingleFileZ#64]
Testing Environment
SingleFileZ 0.5.66
Chrome 84.0.4147.125

SingleFilz File name template i am using is

`{page-title} ({date-iso} {time-locale}) {url-href}.html`

After few test i figure out **{url-href}** causing the problem, its like

`\gildas-lormeau_SingleFileZ_ SingleFileZ is a Web Extension for saving web pages as self-extracting HTML_ZIP hybrid files. (2020-08-18 上午5_49_11) https_\github.com\gildas-lormeau\Singl….html`

Even using
`{url-href}.html`, its also like

`\https_\github.com\gildas-lormeau\SingleFileZ.html`

Remove this variables and problem gone.

i appreciate you still maintain the extension, Thank you so much Gildas.

**Comment by gildas-lormeau** [comment]
@Rupthya Sorry for the laste response, I totally forgot your ticket. I think what you want is `{url-href-flat}`.

**Comment by Rupthya** [comment]
> @Rupthya Sorry for the laste response, I totally forgot your ticket. I think what you want is `{url-href-flat}`.

Thank you problem totally solved, output file name same as {url-href} with old SingleFileZ version.


Just wondering why {url-href} not longer work as OLD version? I appreciate if you feel free to talk about this change.

**Comment by gildas-lormeau** [comment]
Because of this issue https://github.com/gildas-lormeau/SingleFile/issues/461. I agreed suffixing the variable with "-flat" would be a good idea. I also considered this was not a major change.
