### ISSUE TITLE
Tab closes before saving when "automatically close after saving" checked.

### ISSUE THREAD

**Issue by user0022** [gildas-lormeau/SingleFileZ#66]
Hello! Since a few days (less than 1 week maybe), SingleFileZ can't save pages anymore in this way.
That is when in Préférences I check the option: [x] fermer automatiquement l'onglet après l'enregistrement de la page (in french).
The page shades during an half-second and then the tab closes and there is nothing in the download folder.

Since 1 or 2 weeks I used Firefox ESR because my "normal Firefox" had a problem.
So I thought it could be something that happens only in FF ESR, or because of my settings or addons in it.
But I just fixed my normal FF today, with about:support -> Refresh Firefox, which seems to makes FF more fresh than a reinstall. And after not much settings or addons, I see that the problem is the same in it. So it souldn't be on my computer, but more general.

Saving works with:
-SingleFile with "close automatically" unchecked.
-SingleFile with "close automatically" checked.
-SingleFileZ with "close automatically" unchecked.

And it doesn't with:
-SingleFileZ with "close automatically" checked.

Tests that didn't solve the problem:
-Allow "/" in NoScript.
-Disabling addons except SFZ.

I am under Lubuntu 32 bits, and Firfox 80.0.1 or 78.2.0esr. Thank you!

**Comment by gildas-lormeau** [comment]
Thank you for having reported the issue. It was a small mistake I introduced recently. It should be fixed in the version 0.6.10 I just published on the store of Mozilla.

**Comment by user0022** [comment]
OK thanks for very fast correction!
