### ISSUE TITLE
Translation of the description

### ISSUE THREAD

**Issue by gildas-lormeau** [gildas-lormeau/SingleFileZ#7]
Hi @Shitennouji, @xesarni, @rstp14, @womotroll

I created this fork of SingleFile called SingleFileZ some days ago. The "Z" stands for zip. Indeed, pages saved with SingleFileZ are HTML files that are also, in fact, self-extracting ZIP files containing the resources of the saved page. Therefore, saved pages are smaller and can be extracted in order, for example, to get all the images easily. The disadvantages are that JavaScript must be enabled to open saved pages, and Chrome cannot open these files without passing a switch on the command line or installing the extension.  It also takes a little longer to save and open the pages. That's why I published this feature into this separate extension.

The label to update is the description of the extension.
`extensionDescription: "Save web pages as self-extracting HTML/ZIP hybrid files"`

Your help in translating this label would be greatly appreciated ;)

Status:

- [x] German
- [x] English
- [x] French
- [x] Japanese
- [x] Simplified Chinese
- [x] Traditional Chinese
- [x] Russian
- [ ] Polish

**Comment by Shitennouji** [comment]
extensionDescription: "Web ページを自己解凍型の HTML / ZIP ハイブリッドファイルとして保存する"

**Comment by gildas-lormeau** [comment]
Thank you @Shitennouji :)

**Comment by womotroll** [comment]
German Translation:

extensionDescription: "Speichern von Webseiten als selbstentpackende 
HTML/ZIP-Hybriddateien"


Am 29.05.2019 um 22:44 schrieb Gildas:

**Comment by gildas-lormeau** [comment]
Thank you @womotroll :)

**Comment by rstp14** [comment]
extensionDescription: "Сохранение веб-страниц в виде самораспаковывающихся гибридных файлов HTML/ZIP"

**Comment by gildas-lormeau** [comment]
Thank you very much @rstp14
