### ISSUE TITLE
Add 'noindex' meta by default to all saved pages

### ISSUE THREAD

**Issue by gholm** [gildas-lormeau/SingleFileZ#70]
Hi, 

Can `<meta name="robots" content="noindex">` be added by default to all saved pages to avoid getting them indexed by search engines, please?

This is fine for personal pages, but one might not want copyrighted web pages being indexed. Maybe a tickbox feature where the user can choose whether the saves should be indexable or not could work better.

Many thanks!

G.

**Comment by gildas-lormeau** [comment]
There is already `<link rel='canonical' href='...'>` tag in the saved page, isn't is sufficient?

**Comment by gholm** [comment]
I'm afraid I don't see the canonical in the saved pages (using Firefox). 

But to address the substance of your question, canonicalling the page to its original address may achieve the same result as `noindex` in the short run, but could also cause problems for the original website in the long run, for example if they should change the address of that article.

To exemplify, if our downloaded page's canonical points to `https://domain.com/original-page/` and this is changed to `https://domain.com/new-original-page/` after a while, Google might look unfavourably on this discrepance, [since they do ask for exact mapping](https://webmasters.googleblog.com/2009/12/handling-legitimate-cross-domain.html).

I believe that `noindex` is the correct approach here.

**Comment by gildas-lormeau** [comment]
Thank you for your feedback. The canonical was present only in the uncompressed html file. I added it in the main html file too. I also added the hidden option `insertMetaNoIndex`. It's set to `false` by default. To change it, you have to export tour settings, open the file in a text editor, replace `insertMetaNoIndex: false` with `insertMetaNoIndex: true`, save the file and import the saved file in SingleFile(Z). This hidden option will be available in the next version I'll publish.

**Comment by gildas-lormeau** [comment]
I published the new version (version 0.6.15). It's already available for download in Firefox. It will be available in Chrome in the coming days.

**Comment by gholm** [comment]
Excellent, thank you very much for all your work on this! This is a great add-on.
