### ISSUE TITLE
Issue with YANDEX after 6.13

### ISSUE THREAD

**Issue by kramola-RU** [gildas-lormeau/SingleFileZ#72]
Win 10 LTSB x64
Firefox 82 x32

SFZ **6.14**,  SFZ **6.15**

It`s impossible to save pages (whole page and selected part) in YANDEX services.
(stucks on the 1-st step)

For example:  https://zen.yandex.ru/media/id/5f8c2e034ab7c3765a86891b/bezlimitnyi-interenet-bez-oplaty-5f91a9cd2f985a0dd7a72cd2

With the SFZ **6.13** --- no problems.

**Comment by gildas-lormeau** [comment]
It looks like I cannot reproduce the issue. Do you see any errors if you press F12 and click on the "Console" tab?

**Comment by kramola-RU** [comment]
I see errors in both 6.13 and 6.15
[Console.zip](https://github.com/gildas-lormeau/SingleFileZ/files/5425518/Console.zip)

**Comment by gildas-lormeau** [comment]
Thank you, this error is really weird... Could you please try to install manually the extension I attached and tell me if the error still occurs?

[singlefilez-extension-firefox.zip](https://github.com/gildas-lormeau/SingleFileZ/files/5426200/singlefilez-extension-firefox.zip)

**Comment by kramola-RU** [comment]
> tell me if the error still occurs

No error! Thank you!
-----------------------------------
One more Q...
Sometimes  the "Go to..." button is not visible on the infopanel. The button works fine, but it doesn't visible.
I can't understand what it depends on.
![333](https://user-images.githubusercontent.com/51376332/96937870-cb82cf00-14d1-11eb-820d-65501155f27c.jpg)

**Comment by gildas-lormeau** [comment]
I'm sorry but the issue might be more complicated than I expected. I hope I really fixed it now. Could you please test again the file attached?
The issue in the infopanel is weird too... I'll create a separate ticket for it.

[singlefilez-extension-firefox.zip](https://github.com/gildas-lormeau/SingleFileZ/files/5426368/singlefilez-extension-firefox.zip)

**Comment by kramola-RU** [comment]
> Could you please test again the file attached?

Works good. No error.

**Comment by gildas-lormeau** [comment]
Great! It's published :)

**Comment by kramola-RU** [comment]
very very big thanks !
there's not a single problem you can't handle  ;)

**Comment by gildas-lormeau** [comment]
I cheat because I create them actually ;)
