### ISSUE TITLE
Saving a page that uses JavaScript to hide text 

### ISSUE THREAD

**Issue by AdKiller** [gildas-lormeau/SingleFileZ#75]
Is there any way to save a page that uses the following code to hide portions of the text that you have to click to show?

If I save it with SingleFilez, the Show links do not work.
If I save it with Firefox and use HTML page only, the whole text is visible, but most of the formatting is gone and is hard to read.

*** snipped ***

**Comment by gildas-lormeau** [comment]
Did you try the procedure described here? https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages

**Comment by AdKiller** [comment]
> 
> 
> Did you try the procedure described here? https://github.com/gildas-lormeau/SingleFile/blob/master/faq.md#why-dont-interactive-elements-like-folding-titles-dynamic-maps-or-carousels-work-properly-in-saved-pages

That worked! thanks

**Comment by gildas-lormeau** [comment]
You're welcome!
