### ISSUE TITLE
Does this waste hard disk read write cycles?

### ISSUE THREAD

**Issue by keophcp** [gildas-lormeau/SingleFileZ#76]
Just a question. Does opening html file saved via this extension wastes hard disk by writing file to some temp location?
Or directly to RAM? I know that opening such files via 7-zip or winrar extracts them to temp folder and opens them, but what about when opened via Firefox? I tried to use FileActivityWatch by nirsoft, but did not notice any significant disk write use by Firefox or any file or location related to my large html (zip) file with videos. Asking just to be sure.

**Comment by gildas-lormeau** [comment]
I confirm the ZIP file should be uncompressed in RAM when you open it.
