### ISSUE TITLE
Dynamic webpage issue

### ISSUE THREAD

**Issue by CarpetSnack** [gildas-lormeau/SingleFileZ#82]
This may be the same problem as Issue of archive "dynamic" webpage #46.  I'm using macOS 10.15.7 and Chrome Version 87.0.4280.88 (Official Build) (x86_64).  My example site is

 https://www.poorpeoplescampaign.org/resource/policy-and-legislative-priorities/?link_id=1&can_id=63ac0eb141a0d595fbcbadce5a7f3ff5&source=email-14-priorities-for-the-first-100-days-2&email_referrer=email_1015251&email_subject=14-priorities-for-the-first-100-days

I'm unable to expand the drop downs in the 14 Policy Priorities.

**Comment by gildas-lormeau** [comment]
Did you try to disable the setting  Other resources > remove scripts ? It seems to work for me.

**Comment by CarpetSnack** [comment]
Yes, that makes it work.  Thank you for a great extension.

**Comment by gildas-lormeau** [comment]
You're welcome!
