### ISSUE TITLE
Error saving page of certain sites

### ISSUE THREAD

**Issue by boweden** [gildas-lormeau/SingleFileZ#83]
Hello, thanks again for this plugin.

Using SingleFilez with Firefox (although I tried this on Edge as well and had the same result). 
Trying to save the following site:

https://web.archive.org/web/20080609023624/http://wind.prohosting.com/itay82/Info/Files/Maps/Overworld/overworld.htm

gives a "badge value error" and the extension freezes at Step 1 / 3.  

This might be a slightly unrelated problem. Some pages save fine on Edge but not on Firefox.  
For example, the following site:

https://www.the-tipshop.co.uk/cgi-bin/info.pl?name=Zen%20Quest

saves fine on Edge, but freezes at Step 1 / 3 on Firefox.

Thanks again.

**Comment by gildas-lormeau** [comment]
Thank you very much for having reported this regression. I fixed the issue in the version 0.6.43 I just uploaded on the stores. It is available for download on the Mozilla store.

**Comment by boweden** [comment]
Thanks for the quick fix. Everything works fine now :)

**Comment by gildas-lormeau** [comment]
Glad to hear it :)
