### ISSUE TITLE
MacOS Archive Utility etc

### ISSUE THREAD

**Issue by sull** [gildas-lormeau/SingleFileZ#84]
I downloaded the demo files but I have not been able to extract the files using the default Archive Utility app or a few other apps I have installed. I get a .cpgz file when using Archive Utility that just contains the same file as original. Some other apps give an error about unsupported format.

**Comment by gildas-lormeau** [comment]
This might be due to the fact that the files are self-extracting files. These files are valid though, zip softwares that claim to be able to read zip files should be able to open them.
