### ISSUE TITLE
Filename templates aren't working any more

### ISSUE THREAD

**Issue by novoid** [gildas-lormeau/SingleFileZ#85]
Hi,

SingleFileZ 1.0.7, Firefox 85.0.1

I'm using Preferences > File name:
`webarchive/{date-iso}T{hours-locale}.{minutes-locale}.{seconds-locale} myhostname - {url-hostname} - {page-title}.html`

Since Feb 24, the resulting file names changed from:
`2021-02-19T18.03.50 myhostname - www.startpage.com - Startpage.com Search results.html` to
`{date-iso}T{hours-locale}.{minutes-locale}.{seconds-locale} myhostname - www.startpage.com - Startpage.com Search results.html` (actual file name result)

How can I "re-activate" the file name templates?

**Comment by gildas-lormeau** [comment]
Can you update the extension and tell me if the version 1.0.9 fixes the issue? I can't reproduce it.

**Comment by gildas-lormeau** [comment]
That's weird though because this bug existed in the version 1.0.6 and the version 1.0.7 was supposed to fix it...

**Comment by novoid** [comment]
I don't know what caused the issue to occur on multiple on my machines.

The issue is fixed in the meantime without me doing anything. I manually renamed the broken filenames that were accumulated in the meantime and move along.

Sorry for the fuzz.

**Comment by gildas-lormeau** [comment]
No problem! Sorry for the the inconvenience too!
