### ISSUE TITLE
Stuck on saving when "Save raw" is selected.

### ISSUE THREAD

**Issue by rhn** [gildas-lormeau/SingleFileZ#87]
First off, many thanks for the extension, I use it to build up a library of knowledge I can later return to using recoll.

I've come across the issue that saving gets stuck after showing the status rectangle a couple of times, but only properly investigated now.

To reproduce:

1. Turn on preference "HTML content" -> "save raw page".
2. Go to https://lareviewofbooks.org/article/the-machine-stops-science-and-its-limits/
3. Save page using the SingleFileZ icon on the top bar.

Result:

White rectangle on the bottom left appears, and stays there for minutes. CPU activity goes up, network activity picks up into tens of kilobytes per second. No file saved.

Expected:

Completed saving within a minute, no network activity during that time.

**Comment by gildas-lormeau** [comment]
Thank you having reported this issue. It's fixed in the version `1.0.15` I just uploaded.
