### ISSUE TITLE
"View Image" and "Save Image As..." don't work as they probably should

### ISSUE THREAD

**Issue by lkintact** [gildas-lormeau/SingleFileZ#90]
(This has some relation to gildas-lormeau/SingleFile#645).

**To Reproduce**
1. Create a new Firefox profile, add SingleFileZ to it (don't enable "Allow this extension to run in Private Windows" when adding SFZ).
2. Save the page at http://www.photographers1.com/Sailing/NauticalTerms&Nomenclature.html with SFZ, open the saved file.
3. Search for `DANGER ZONE !!!` in the page, one match will be found with an image below: a white ship hull in a circle with black sector, titled "Bearings of Objects in Relation to Your Vessel".
4. Right-click on the image and click on "View Image". A dialogue like this pops up:

![capture](https://user-images.githubusercontent.com/24726299/112999839-f572a880-9177-11eb-8430-ee7850de70d9.jpg)
5. Right-click on the image and click on "Save Image As...". A "Save Image" dialogue pops up with the prefilled filename `index.gif`.

**Expected behavior**
The image should perhaps be shown in the current browser tab at step 4.
The prefilled filename should be `Bearings.gif` at step 5.

**Environment**
 - OS: Windows 10 Home 1803
 - Browser: Firefox version 87.0 (32-bit)
 - SingleFileZ version 1.0.18.

**Comment by gildas-lormeau** [comment]
That looks indeed a bug since the extension of the URL was ".gif", I'll try to see what's wrong this weekend.

**Comment by gildas-lormeau** [comment]
This issue is fixed in the version 1.0.19

**Comment by lkintact** [comment]
Just tried version 1.0.19, "View image" works for me.
> The URL of the image resource can be found in the index.json file in the zip. Each entry in the zip file has also as comment the URL of the resource.

Thanks for letting know!
