### ISSUE TITLE
Selfhost *.html can't open with chrome directly

### ISSUE THREAD

**Issue by Jvcon** [gildas-lormeau/SingleFileZ#92]
I hosted *.html with nginx

`
server{
        root /var/www/web/;
        location / {
              index index.html;
              autoindex on;
        }
}
`

When I open it in Chrome, it still like that:

`
Error: Cannot open the page from the filesystem.
Chrome: Install SingleFileZ and enable the option "Allow access to file URLs" in the details page of the extension (chrome://extensions/?id=offkdfbbigofcgdokjemgjpdockaafjg). Otherwise, start the browser with the switch "--allow-file-access-from-files".
Microsoft Edge: Install SingleFileZ and enable the option "Allow access to file URLs" in the details page of the extension (edge://extensions/?id=gofneaifncimeglaecpnanbnmnpfjekk). Otherwise, start the browser with the switch "--allow-file-access-from-files".
Safari: Select "Disable Local File Restrictions" in the "Develop" menu.
`

**Comment by gildas-lormeau** [comment]
You probably made something wrong. Pages can be hosted on a HTTP server (without needing the extension to be installed), cf. this page for example: https://gildas-lormeau.github.io/
